### ISSUE TITLE
After invoking Ctrl+T search stops and fzf hangs after typing the first character 

### ISSUE THREAD

**Issue by ntpeters** [kelleyma49/PSFzf#87] opened 2021-08-30 20:04 UTC
### Repro Steps:

1. Open a PowerShell Core instance in Windows Terminal
2. Press Ctrl+T
2. Type a search term

> **NOTE:** Ctrl+R to search history works perfectly fine

### Expected Behavior

Search is refined by the entered text, and am able to select a result with the arrow keys.

### Actual Behavior

Search stops after the first character is entered, and fzf seems to freeze as it's no longer responsive to arrow keys or the escape key. It's possible to only backspace up to the first character entered, but it doesn't allow deleting that first character. Pressing enter selects the first entry, otherwise the only way to exit is Ctrl+C as it's not responsive to escape.

### Screenshots

After entering a search term:
![image](https://user-images.githubusercontent.com/1189211/131396575-1ea0f736-6dc7-4ad4-8796-5f801dfab4e2.png)

After attempting to delete the entire search term:
![image](https://user-images.githubusercontent.com/1189211/131396604-3072db7f-a8e4-4132-8e79-5d5ce11fd34c.png)

### Versions

- PSFzf: 2.2.8 and 2.2.6
- PSReadline: 2.1.0
- PowerShell Core: 7.1.4
  - Also repros in Windows PowerShell 5.1, but allows backspacing to delete the entire search term with otherwise identical behavior
- Windows Terminal: 1.10.2383.0

### PowerShell Profile

Relevant lines in my profile:

```powershell
Import-Module PSFzf
Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
```

### Environment

`FZF_DEFAULT_COMMAND = 'fd --type file'`

**Comment by ntpeters** [comment] 2021-08-31 00:26
I think I found the issue. This line appears to be the problem:
https://github.com/kelleyma49/PSFzf/blob/b97263a30addd9a2c84a8603382c92e4e6de0eeb/PSFzf.Base.ps1#L49

This should be invoking the command directly, rather than through `cmd`. If I make that change locally it seems to work fine. Looks like this should also be using the quoted directory path here too.

Beyond this fix, it'd be nice to have additional options (via`Set-PSFzfOption`) to explicitly specify a format string for this command along with options to provide args for searching by directory only and colorization.

**Comment by kelleyma49** [comment] 2021-09-08 05:14
The intended behavior is to pass the command to the native shell. 

I believe the actual problem you are seeing is related to a regression I introduced into `fzf` itself a couple of months back. I have fixed the regression (https://github.com/junegunn/fzf/pull/2580), but `fzf` hasn't had an update in a couple of months. If you're setup to build go binaries, you can check out `fzf`'s head to test the fix.

**Comment by kelleyma49** [comment] 2021-11-06 18:42
fzf versions great than 0.27.3 should resolve this problem, so I'm closing this for now. Let me know if you see it again.

**Closed by kelleyma49** 2021-11-06 18:42 UTC
